package sk.upjs.ics.paz.gui;

import java.math.BigDecimal;
import sk.upjs.ics.paz.entity.Pouzivatel;
import sk.upjs.ics.paz.dao.Factory;
import sk.upjs.ics.paz.dao.StrediskaDao;

public class NajdiNajblizsieForm extends javax.swing.JDialog {

    private final Pouzivatel pouzivatel = Factory.INSTANCE.getPouzivatel();
    private final StrediskaDao strediskaDao = Factory.INSTANCE.getStrediskaDao();

    /**
     * Creates new form NajdiNajblizsieForm
     *
     * @param parent rodicovske okno
     * @param modal ci je okno modalne
     */
    public NajdiNajblizsieForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // ak ma pouzivatel zadane suradnice (nepovinny udaj pri registracii),
        // tak sa nacitaju a nemusi ich zadavat
        if (pouzivatel != null) {
            if (pouzivatel.getGpsDlzka() != null && pouzivatel.getGpsSirka() != null) {
                txtDlzka.setText(pouzivatel.getGpsDlzka().toString());
                txtSirka.setText(pouzivatel.getGpsSirka().toString());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblZadajtePolohu = new javax.swing.JLabel();
        lblSirka = new javax.swing.JLabel();
        lblDlzka = new javax.swing.JLabel();
        txtSirka = new javax.swing.JTextField();
        txtDlzka = new javax.swing.JTextField();
        lblOkruh = new javax.swing.JLabel();
        txtOkruh = new javax.swing.JTextField();
        lblKilometre = new javax.swing.JLabel();
        btnNajdi = new javax.swing.JButton();
        btnStorno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nájdi najbližšie stredisko");
        setResizable(false);

        lblZadajtePolohu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblZadajtePolohu.setText("Zadajte svoju polohu:");

        lblSirka.setText("Šírka:");

        lblDlzka.setText("Dĺžka:");

        txtSirka.setName("Šírka"); // NOI18N

        txtDlzka.setName("Dĺžka"); // NOI18N

        lblOkruh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOkruh.setText("V akom okruhu chcete vyhľadávať?");

        txtOkruh.setName("Okruh"); // NOI18N

        lblKilometre.setText("kilometrov");

        btnNajdi.setText("Nájdi");
        btnNajdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNajdiActionPerformed(evt);
            }
        });

        btnStorno.setText("Storno");
        btnStorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStornoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblZadajtePolohu)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDlzka)
                            .addComponent(lblSirka))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSirka, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDlzka, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblOkruh)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtOkruh, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKilometre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnNajdi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStorno)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblZadajtePolohu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSirka)
                    .addComponent(txtSirka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDlzka)
                    .addComponent(txtDlzka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(lblOkruh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOkruh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKilometre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStorno)
                    .addComponent(btnNajdi))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStornoActionPerformed
        dispose();
    }//GEN-LAST:event_btnStornoActionPerformed

    /**
     * Ziska zoznam stredisk v danom okruhu, ale este ho nevie zobrazit v
     * hlavnom formulari :-(
     *
     * @param evt
     */
    private void btnNajdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNajdiActionPerformed
        if (!suPoliaDobre()) {
            return;
        }

        double okruh = Double.parseDouble(txtOkruh.getText());
        Factory.INSTANCE.setVlastnyZoznam(strediskaDao.najdiStrediskaVOkruhu(new BigDecimal(txtSirka.getText()),
                new BigDecimal(txtDlzka.getText()), okruh));
        dispose();
    }//GEN-LAST:event_btnNajdiActionPerformed

    private boolean suPoliaDobre() {
        boolean poliaSuDobre = true;
        VerifikatorVstupov verifikatorVstupov = new VerifikatorVstupov();
        if (!verifikatorVstupov.jeNeprazdny(txtOkruh)) {
            verifikatorVstupov.hlaskaPrazdnyAleboDlhyString(this, txtOkruh, 30);
            return false;
        } else if (!verifikatorVstupov.jeDesatinneCislo(txtOkruh)) {
            verifikatorVstupov.hlaskaCisloNieJeVSpravnomFormate(this, txtOkruh);
            return false;
        }
        if (!verifikatorVstupov.jeNeprazdny(txtSirka)) {
            verifikatorVstupov.hlaskaPrazdnyAleboDlhyString(this, txtSirka, 30);
            return false;
        } else if (!verifikatorVstupov.jeDesatinneCislo(txtSirka)) {
            verifikatorVstupov.hlaskaCisloNieJeVSpravnomFormate(this, txtSirka);
            return false;
        }
        if (!verifikatorVstupov.jeNeprazdny(txtDlzka)) {
            verifikatorVstupov.hlaskaPrazdnyAleboDlhyString(this, txtDlzka, 30);
            return false;
        } else if (!verifikatorVstupov.jeDesatinneCislo(txtDlzka)) {
            verifikatorVstupov.hlaskaCisloNieJeVSpravnomFormate(this, txtDlzka);
            return false;
        }

        return poliaSuDobre;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NajdiNajblizsieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NajdiNajblizsieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NajdiNajblizsieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NajdiNajblizsieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NajdiNajblizsieForm dialog = new NajdiNajblizsieForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNajdi;
    private javax.swing.JButton btnStorno;
    private javax.swing.JLabel lblDlzka;
    private javax.swing.JLabel lblKilometre;
    private javax.swing.JLabel lblOkruh;
    private javax.swing.JLabel lblSirka;
    private javax.swing.JLabel lblZadajtePolohu;
    private javax.swing.JTextField txtDlzka;
    private javax.swing.JTextField txtOkruh;
    private javax.swing.JTextField txtSirka;
    // End of variables declaration//GEN-END:variables
}
