package sk.upjs.ics.paz.gui;

import java.math.BigDecimal;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import sk.upjs.ics.paz.dao.Factory;
import sk.upjs.ics.paz.dao.FiltreDao;
import sk.upjs.ics.paz.entity.Filter;
import sk.upjs.ics.paz.entity.Pouzivatel;

public class PridajUpravFilterForm extends javax.swing.JDialog {

    Filter filter;
    FiltreDao filtreDao = Factory.INSTANCE.getFiltreDao();
    Pouzivatel pouzivatel = Factory.INSTANCE.getPouzivatel();

    /**
     * Creates new form PridajUpravFilterForm
     */
    public PridajUpravFilterForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Konstruktor okna pre pridanie noveho filtra
     *
     * @param parent rodicovske okno
     */
    public PridajUpravFilterForm(java.awt.Frame parent) {
        this(parent, true);
        this.filter = new Filter();
        this.setTitle("Pridanie nového filtra");
    }

    /**
     * Konstruktor okna pre upravu existujuceho filtra
     *
     * @param parent rodicovske okno
     * @param filter filter, ktory upravujeme
     */
    public PridajUpravFilterForm(java.awt.Frame parent, Filter filter) {
        this.filter = filter;
        this.setTitle("Úprava filtra");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNazov = new javax.swing.JLabel();
        txtNazov = new javax.swing.JTextField();
        lblMinVyskaSnehu = new javax.swing.JLabel();
        txtMinVyskaSnehu = new javax.swing.JTextField();
        lblCm = new javax.swing.JLabel();
        lblNazovObsahuje = new javax.swing.JLabel();
        txtNazovObsahuje = new javax.swing.JTextField();
        lblMinPodmienky = new javax.swing.JLabel();
        cmbMinPodmienky = new javax.swing.JComboBox();
        lblMinPocetVlekov = new javax.swing.JLabel();
        txtMinPocetVlekov = new javax.swing.JTextField();
        lblMinPocetLanoviek = new javax.swing.JLabel();
        txtMinPocetLanoviek = new javax.swing.JTextField();
        lblMinPocetTrati = new javax.swing.JLabel();
        txtMinPocetTrati = new javax.swing.JTextField();
        lblMaxCenyListkov = new javax.swing.JLabel();
        lblMaxCenaListkaDospely = new javax.swing.JLabel();
        lblMaxCenaListkaDieta = new javax.swing.JLabel();
        lblMaxCenaListkaStudent = new javax.swing.JLabel();
        txtMaxCenaListkaDospely = new javax.swing.JTextField();
        txtMaxCenaListkaDieta = new javax.swing.JTextField();
        txtMaxCenaListkaStudent = new javax.swing.JTextField();
        lblEuro1 = new javax.swing.JLabel();
        lblEuro2 = new javax.swing.JLabel();
        lblEuro3 = new javax.swing.JLabel();
        chkDaSaPozicatVystroj = new javax.swing.JCheckBox();
        chkDaSaUbytovat = new javax.swing.JCheckBox();
        btnStorno = new javax.swing.JButton();
        btnUloz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNazov.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNazov.setText("Názov filtra:");

        lblMinVyskaSnehu.setText("Minimálna výška snehu:");

        lblCm.setText("cm");

        lblNazovObsahuje.setText("Názov strediska obsahuje:");

        lblMinPodmienky.setText("Minimálne podmienky:");

        cmbMinPodmienky.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "nezadané", "výborné", "veľmi dobré", "dobré", "obmedzené", "nevyhovujúce" }));

        lblMinPocetVlekov.setText("Minimálny počet vlekov v prevádzke:");

        lblMinPocetLanoviek.setText("Minimálny počet lanoviek v prevádzke:");

        lblMinPocetTrati.setText("Minimálny počet tratí v prevádzke:");

        lblMaxCenyListkov.setText("Maximálne ceny lístkov");

        lblMaxCenaListkaDospely.setText("Dospelý:");

        lblMaxCenaListkaDieta.setText("Dieťa:");

        lblMaxCenaListkaStudent.setText("Študent:");

        lblEuro1.setText("€");

        lblEuro2.setText("€");

        lblEuro3.setText("€");

        chkDaSaPozicatVystroj.setText("nutná možnosť zapožičania výstroje");

        chkDaSaUbytovat.setText("nutná možnosť ubytovania");

        btnStorno.setText("Storno");

        btnUloz.setText("Ulož");
        btnUloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlozActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkDaSaUbytovat)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblNazovObsahuje)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNazovObsahuje, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMinVyskaSnehu)
                                .addComponent(lblMinPodmienky))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtMinVyskaSnehu)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblCm))
                                .addComponent(cmbMinPodmienky, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNazov)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNazov, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMinPocetVlekov)
                            .addComponent(lblMinPocetLanoviek)
                            .addComponent(lblMinPocetTrati))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMinPocetVlekov)
                            .addComponent(txtMinPocetLanoviek)
                            .addComponent(txtMinPocetTrati, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                    .addComponent(lblMaxCenyListkov)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblMaxCenaListkaStudent)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaxCenaListkaStudent))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblMaxCenaListkaDieta)
                                .addGap(30, 30, 30)
                                .addComponent(txtMaxCenaListkaDieta))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblMaxCenaListkaDospely)
                                .addGap(18, 18, 18)
                                .addComponent(txtMaxCenaListkaDospely, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEuro1)
                            .addComponent(lblEuro2)
                            .addComponent(lblEuro3)))
                    .addComponent(chkDaSaPozicatVystroj))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUloz, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStorno, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNazov)
                    .addComponent(txtNazov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNazovObsahuje)
                    .addComponent(txtNazovObsahuje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinVyskaSnehu)
                    .addComponent(txtMinVyskaSnehu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinPodmienky)
                    .addComponent(cmbMinPodmienky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMaxCenyListkov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxCenaListkaDospely)
                    .addComponent(txtMaxCenaListkaDospely, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEuro1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxCenaListkaDieta)
                    .addComponent(txtMaxCenaListkaDieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEuro2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxCenaListkaStudent)
                    .addComponent(txtMaxCenaListkaStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEuro3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinPocetVlekov)
                    .addComponent(txtMinPocetVlekov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinPocetLanoviek)
                    .addComponent(txtMinPocetLanoviek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinPocetTrati)
                    .addComponent(txtMinPocetTrati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chkDaSaPozicatVystroj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDaSaUbytovat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStorno)
                    .addComponent(btnUloz))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUlozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlozActionPerformed
        filter.setMenoUzivatela(pouzivatel.getMeno());

        if (overVyplneniePola(txtNazov)) {
            filter.setNazov(txtNazov.getText());
        } else {
            return;
        }

        if (!txtNazovObsahuje.getText().equals("")) {
            filter.setNazovObsahuje(txtNazovObsahuje.getText());
        } else {
            filter.setNazovObsahuje(null);
        }

        if (!txtMinVyskaSnehu.getText().equals("")) {
            filter.setMinVyskaSnehu(new Integer(txtMinVyskaSnehu.getText()));
        } else {
            filter.setMinVyskaSnehu(0);
        }

        filter.setMinPodmienky(cmbMinPodmienky.getSelectedItem().toString());

        if (!txtMinPocetVlekov.getText().equals("")) {
            filter.setMinPocetVlekovVPrevadzke(new Integer(txtMinPocetVlekov.getText()));
        } else {
            filter.setMinPocetVlekovVPrevadzke(0);
        }

        if (!txtMinPocetLanoviek.getText().equals("")) {
            filter.setMinPocetLanoviekVPrevadzke(new Integer(txtMinPocetLanoviek.getText()));
        } else {
            filter.setMinPocetLanoviekVPrevadzke(0);
        }

        if (!txtMinPocetTrati.getText().equals("")) {
            filter.setMinPocetTratiVPrevadzke(new Integer(txtMinPocetTrati.getText()));
        } else {
            filter.setMinPocetTratiVPrevadzke(0);
        }

        if (!txtMaxCenaListkaDospely.getText().equals("")) {
            filter.setMaxCenaListkaDospely(new BigDecimal(txtMaxCenaListkaDospely.getText()));
        } else {
            filter.setMaxCenaListkaDospely(null);
        }

        if (!txtMaxCenaListkaDieta.getText().equals("")) {
            filter.setMaxCenaListkaDieta(new BigDecimal(txtMaxCenaListkaDieta.getText()));
        } else {
            filter.setMaxCenaListkaDieta(null);
        }

        if (!txtMaxCenaListkaStudent.getText().equals("")) {
            filter.setMaxCenaListkaStudent(new BigDecimal(txtMaxCenaListkaStudent.getText()));
        } else {
            filter.setMaxCenaListkaStudent(null);
        }

        filter.setNutnostPozicatVystroj(chkDaSaPozicatVystroj.isSelected());
        filter.setNutnostUbytovat(chkDaSaUbytovat.isSelected());

        filtreDao.uloz(filter);
        dispose();

    }//GEN-LAST:event_btnUlozActionPerformed

    /**
     * Overi, ci je dane pole vyplnene, ak nie, vyhodi o tom hlasku
     *
     * @param pole pole, ktore musi byt vyplnene
     */
    private boolean overVyplneniePola(javax.swing.JTextField pole) {
        if (pole.getText().equals("")) {
            String sprava = "Prosím vyplňte pole " + pole.getName();
            String nadpis = "Chyba - nevyplnené pole";
            JOptionPane.showMessageDialog(this, sprava, nadpis, ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PridajUpravFilterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PridajUpravFilterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PridajUpravFilterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PridajUpravFilterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PridajUpravFilterForm dialog = new PridajUpravFilterForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStorno;
    private javax.swing.JButton btnUloz;
    private javax.swing.JCheckBox chkDaSaPozicatVystroj;
    private javax.swing.JCheckBox chkDaSaUbytovat;
    private javax.swing.JComboBox cmbMinPodmienky;
    private javax.swing.JLabel lblCm;
    private javax.swing.JLabel lblEuro1;
    private javax.swing.JLabel lblEuro2;
    private javax.swing.JLabel lblEuro3;
    private javax.swing.JLabel lblMaxCenaListkaDieta;
    private javax.swing.JLabel lblMaxCenaListkaDospely;
    private javax.swing.JLabel lblMaxCenaListkaStudent;
    private javax.swing.JLabel lblMaxCenyListkov;
    private javax.swing.JLabel lblMinPocetLanoviek;
    private javax.swing.JLabel lblMinPocetTrati;
    private javax.swing.JLabel lblMinPocetVlekov;
    private javax.swing.JLabel lblMinPodmienky;
    private javax.swing.JLabel lblMinVyskaSnehu;
    private javax.swing.JLabel lblNazov;
    private javax.swing.JLabel lblNazovObsahuje;
    private javax.swing.JTextField txtMaxCenaListkaDieta;
    private javax.swing.JTextField txtMaxCenaListkaDospely;
    private javax.swing.JTextField txtMaxCenaListkaStudent;
    private javax.swing.JTextField txtMinPocetLanoviek;
    private javax.swing.JTextField txtMinPocetTrati;
    private javax.swing.JTextField txtMinPocetVlekov;
    private javax.swing.JTextField txtMinVyskaSnehu;
    private javax.swing.JTextField txtNazov;
    private javax.swing.JTextField txtNazovObsahuje;
    // End of variables declaration//GEN-END:variables
}
