package sk.upjs.ics.paz.gui;

import sk.upjs.ics.paz.entity.Stredisko;

public class ZobrazDetailStrediskaForm extends javax.swing.JDialog {

    private Stredisko stredisko;

    /**
     * Creates new form ZobrazDetailForm
     *
     * @param parent rodicovske okno
     * @param modal ci je okno modalne
     */
    public ZobrazDetailStrediskaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Vytvori formular, ktory zobrazi detail konkretneho strediska
     *
     * @param parent rodicovske okno
     * @param stredisko stredisko, ktore zobrazujeme
     */
    public ZobrazDetailStrediskaForm(java.awt.Frame parent, Stredisko stredisko) {
        this(parent, true);
        this.stredisko = stredisko;

        lblNazov.setText(stredisko.getNazov());
        lblVyskaSnehu.setText(String.valueOf("Výška snehu: " + stredisko.getVyskaSnehu() + " cm"));
        lblPodmienky.setText("Podmienky: " + stredisko.getPodmienky());
        lblPocetVlekov.setText("Počet vlekov: "
                + String.valueOf(stredisko.getPocetVlekovVPrevadzke())
                + "/"
                + String.valueOf(stredisko.getPocetVlekov()));
        lblPocetLanoviek.setText("Počet lanoviek: "
                + String.valueOf(stredisko.getPocetLanoviekVPrevadzke())
                + "/"
                + String.valueOf(stredisko.getPocetLanoviek()));
        lblPocetTrati.setText("Počet tratí: "
                + String.valueOf(stredisko.getPocetTratiVPrevadzke())
                + "/"
                + String.valueOf(stredisko.getPocetTrati()));
        lblCenaDospely.setText("Dospelý: "
                + stredisko.getCenaListkaDospely()
                + " €");
        lblCenaDieta.setText("Dieťa: "
                + stredisko.getCenaListkaDieta()
                + " €");
        lblCenaStudent.setText("Študent: "
                + stredisko.getCenaListkaStudent()
                + " €");

        lblPozicanieVystroje.setText("možnosť požičania výstroje: " + dajAnoNie(stredisko.isDaSaPozicatVystroj()));
        lblUbytovanie.setText("možnosť ubytovania: " + dajAnoNie(stredisko.isDaSaUbytovat()));
        
        lblGpsSirka.setText("GPS šírka: " + stredisko.getGpsSirka());
        lblGpsDlzka.setText("GPS dĺžka: " + stredisko.getGpsDlzka());
    }

    /**
     * @param b boolovska hodnota
     * @return slovna reprezentacia b (ano/nie)
     */
    private String dajAnoNie(boolean b) {
        if (b) {
            return "áno";
        } else {
            return "nie";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNazov = new javax.swing.JLabel();
        lblVyskaSnehu = new javax.swing.JLabel();
        lblPodmienky = new javax.swing.JLabel();
        lblPocetVlekov = new javax.swing.JLabel();
        lblPocetLanoviek = new javax.swing.JLabel();
        lblPocetTrati = new javax.swing.JLabel();
        lblCeny = new javax.swing.JLabel();
        lblCenaDospely = new javax.swing.JLabel();
        lblCenaDieta = new javax.swing.JLabel();
        lblCenaStudent = new javax.swing.JLabel();
        lblGpsSuradnice = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblGpsSirka = new javax.swing.JLabel();
        lblGpsDlzka = new javax.swing.JLabel();
        lblPozicanieVystroje = new javax.swing.JLabel();
        lblUbytovanie = new javax.swing.JLabel();
        lblParametre = new javax.swing.JLabel();
        lblSluzby = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail strediska");
        setResizable(false);

        lblNazov.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNazov.setText("Názov strediska");

        lblVyskaSnehu.setText("Výška snehu");

        lblPodmienky.setText("Podmienky");

        lblPocetVlekov.setText("Počet vlekov (v prevádzke/všetkých)");

        lblPocetLanoviek.setText("Počet lanoviek");

        lblPocetTrati.setText("Počet tratí");

        lblCeny.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCeny.setText("Ceny lístkov");

        lblCenaDospely.setText("Dospelý");

        lblCenaDieta.setText("Dieťa");

        lblCenaStudent.setText("Študent");

        lblGpsSuradnice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGpsSuradnice.setText("GPS súradnice");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblGpsSirka.setText("GPS šírka");

        lblGpsDlzka.setText("GPS dĺžka");

        lblPozicanieVystroje.setText("možnosť požičania výstroje");

        lblUbytovanie.setText("možnosť ubytovania");

        lblParametre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblParametre.setText("Parametre (v prevádzke/všetky)");

        lblSluzby.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSluzby.setText("Služby");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNazov)
                            .addComponent(lblPodmienky)
                            .addComponent(lblVyskaSnehu))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGpsDlzka)
                            .addComponent(lblGpsSuradnice)
                            .addComponent(lblGpsSirka)
                            .addComponent(lblParametre)
                            .addComponent(lblPocetVlekov)
                            .addComponent(lblPocetLanoviek)
                            .addComponent(lblPocetTrati))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCenaDieta)
                            .addComponent(lblCeny)
                            .addComponent(lblCenaDospely)
                            .addComponent(lblCenaStudent)
                            .addComponent(lblUbytovanie)
                            .addComponent(lblPozicanieVystroje)
                            .addComponent(lblSluzby))
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNazov)
                .addGap(18, 18, 18)
                .addComponent(lblVyskaSnehu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPodmienky)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblParametre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPocetVlekov)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPocetLanoviek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPocetTrati)
                        .addGap(18, 18, 18)
                        .addComponent(lblGpsSuradnice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGpsSirka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGpsDlzka))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCeny)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCenaDospely)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCenaDieta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCenaStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSluzby)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPozicanieVystroje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUbytovanie)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZobrazDetailStrediskaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZobrazDetailStrediskaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZobrazDetailStrediskaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZobrazDetailStrediskaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ZobrazDetailStrediskaForm dialog = new ZobrazDetailStrediskaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCenaDieta;
    private javax.swing.JLabel lblCenaDospely;
    private javax.swing.JLabel lblCenaStudent;
    private javax.swing.JLabel lblCeny;
    private javax.swing.JLabel lblGpsDlzka;
    private javax.swing.JLabel lblGpsSirka;
    private javax.swing.JLabel lblGpsSuradnice;
    private javax.swing.JLabel lblNazov;
    private javax.swing.JLabel lblParametre;
    private javax.swing.JLabel lblPocetLanoviek;
    private javax.swing.JLabel lblPocetTrati;
    private javax.swing.JLabel lblPocetVlekov;
    private javax.swing.JLabel lblPodmienky;
    private javax.swing.JLabel lblPozicanieVystroje;
    private javax.swing.JLabel lblSluzby;
    private javax.swing.JLabel lblUbytovanie;
    private javax.swing.JLabel lblVyskaSnehu;
    // End of variables declaration//GEN-END:variables
}
